### ISSUE TITLE
Renode crash when --console used in Eclipse launcher

### ISSUE THREAD

**Issue by AntonKrug** [renode/renode#187]
When using the --console in Eclipse's external launcher I'm getting Unhandled Exception error. The --console which should move the monitor to the console, however Eclipse which puts the console into their own tab (instead of standalone window), that combination is causing a problem:

![console](https://user-images.githubusercontent.com/30338596/108836871-4fa4aa80-75c9-11eb-86e0-471cb42dc9cd.JPG)

Fatal error:
The handle is invalid.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.Console.set_TreatControlCAsInput(Boolean value)
   at Antmicro.Renode.UI.ConsoleIOSource..ctor()
   at Antmicro.Renode.UI.CommandLineInterface.PrepareShell(Options options, Monitor monitor)
   at Antmicro.Renode.UI.CommandLineInterface.Run(Options options, Action`1 beforeRun)
   at Antmicro.Renode.Program.<>c__DisplayClass0_0.<Main>b__1()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

Unhandled Exception: System.IO.IOException: The handle is invalid.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.Console.set_TreatControlCAsInput(Boolean value)
   at Antmicro.Renode.UI.ConsoleIOSource..ctor()
   at Antmicro.Renode.UI.CommandLineInterface.PrepareShell(Options options, Monitor monitor)
   at Antmicro.Renode.UI.CommandLineInterface.Run(Options options, Action`1 beforeRun)
   at Antmicro.Renode.Program.<>c__DisplayClass0_0.<Main>b__1()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

**Comment by mateusz-holenko** [comment]
This is fixed in: https://github.com/renode/renode-infrastructure/commit/99ebd4d8b5737b00267a439ca3200066f7964121.
