### ISSUE TITLE
`renode -v` crashes

### ISSUE THREAD

**Issue by xobs** [renode/renode#305]
Running Renode 2022-02-28 nightly on Windows:

```
$ renode -v
Fatal error:
The type initializer for 'Antmicro.Renode.Core.EmulationManager' threw an exception.
   at Antmicro.Renode.Core.EmulationManager.get_Instance()
   at Antmicro.Renode.UI.CommandLineInterface.Run(Options options, Action`1 beforeRun)
   at Antmicro.Renode.Program.<>c__DisplayClass0_0.<Main>b__1()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
Inner exception:
The type initializer for 'Antmicro.Renode.Utilities.TypeManager' threw an exception.
   at Antmicro.Renode.Utilities.TypeManager.get_Instance()
   at Antmicro.Renode.Peripherals.BackendManager.Init()
   at Antmicro.Renode.Core.Emulation..ctor()
   at Antmicro.Renode.Core.EmulationManager..ctor()
   at Antmicro.Renode.Core.EmulationManager.RebuildInstance()
   at Antmicro.Renode.Core.EmulationManager..cctor()
Inner exception:
Method 'TryDisassembleInstruction' in type 'Antmicro.Renode.Disassembler.LLVM.LLVMDisassembler' from assembly 'LLVMDisassembler, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
   at System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMarkHandle stackMark, IntPtr pPrivHostBinder, Boolean loadTypeFromPartialName, ObjectHandleOnStack type)
   at System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean loadTypeFromPartialName)
   at System.Type.GetType(String typeName)
   at Antmicro.Renode.Utilities.TypeManager.GetTypeWithLazyLoad(String name, String assemblyFullName, String path)
   at Antmicro.Renode.Utilities.TypeManager.AnalyzeAssembly(String path, Boolean bundled, Boolean throwOnBadImage)
   at Antmicro.Renode.Utilities.TypeManager.ScanInner(String path, Boolean recursive)
   at Antmicro.Renode.Utilities.TypeManager.Scan(String path, Boolean recursive)
   at Antmicro.Renode.Utilities.TypeManager..cctor()


Unhandled Exception: System.TypeInitializationException: The type initializer for 'Antmicro.Renode.Core.EmulationManager' threw an exception. ---> System.TypeInitializationException: The type initializer for 'Antmicro.Renode.Utilities.TypeManager' threw an exception. ---> System.TypeLoadException: Method 'TryDisassembleInstruction' in type 'Antmicro.Renode.Disassembler.LLVM.LLVMDisassembler' from assembly 'LLVMDisassembler, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
   at System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMarkHandle stackMark, IntPtr pPrivHostBinder, Boolean loadTypeFromPartialName, ObjectHandleOnStack type)
   at System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean loadTypeFromPartialName)
   at System.Type.GetType(String typeName)
   at Antmicro.Renode.Utilities.TypeManager.GetTypeWithLazyLoad(String name, String assemblyFullName, String path)
   at Antmicro.Renode.Utilities.TypeManager.AnalyzeAssembly(String path, Boolean bundled, Boolean throwOnBadImage)
   at Antmicro.Renode.Utilities.TypeManager.ScanInner(String path, Boolean recursive)
   at Antmicro.Renode.Utilities.TypeManager.Scan(String path, Boolean recursive)
   at Antmicro.Renode.Utilities.TypeManager..cctor()
   --- End of inner exception stack trace ---
   at Antmicro.Renode.Utilities.TypeManager.get_Instance()
   at Antmicro.Renode.Peripherals.BackendManager.Init()
   at Antmicro.Renode.Core.Emulation..ctor()
   at Antmicro.Renode.Core.EmulationManager..ctor()
   at Antmicro.Renode.Core.EmulationManager.RebuildInstance()
   at Antmicro.Renode.Core.EmulationManager..cctor()
   --- End of inner exception stack trace ---
   at Antmicro.Renode.Core.EmulationManager.get_Instance()
   at Antmicro.Renode.UI.CommandLineInterface.Run(Options options, Action`1 beforeRun)
   at Antmicro.Renode.Program.<>c__DisplayClass0_0.<Main>b__1()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

$

**Comment by xobs** [comment]
This may be due to the fact that `renode-latest` installed over `renode-1.12` without first uninstalling it.

Uninstalling both versions then installing them again works. There should probably be a check to make sure Renode doesn't get installed over an existing version.
