### ISSUE TITLE
Crash in USBIPServer when submitting underfilled USB buffer

### ISSUE THREAD

**Issue by xobs** [renode/renode#517]
### Description

When submitting an underfilled USB buffer, the USBIPServer will attempt to decode the packet before sending it out the wire. If a packet is insufficiently full, this will result in a crash of the emulator.

It's unclear whether this is a bug in Renode, or if it's considered acceptable for malformed programs to crash the emulator.

This was discovered in the Precursor version of the SpinalHDL USB core. USB/IP requests 18 bytes as part of the first packet, whereas most hardware will request 8 bytes. I believe this discrepancy between USB/IP and hardware has uncovered an issue in the software, however it is questionable whether the issue lies in Renode or in the software-under-test.

### Expected behaviour

Renode itself shouldn't crash.

### How to reproduce?

Create a `USBDeviceCore` and pass it a `customSetupPacketHandler`. Then, in the custom setup packet handler, call `resultCallback` with a smaller-than-expected number of bytes. For example, if the descriptor requests 18 bytes, return only 8 bytes.

### Environment

Please, provide the following information:

- OS: Linux and Windows
- Renode version (with commit SHA): f2389ae9e7f2d7ddf469f34609410a8aee1807f4

### Additional information

When the crash occurs, the following backtrace can be seen:

```
Could not decode the packet of type Antmicro.Renode.Extensions.Utilities.USB.DeviceDescriptor due to insufficient data. Required 18 bytes, but received 8
  at Antmicro.Renode.Utilities.Packets.Packet.Decode[T] (System.Collections.Generic.IList`1[T] data, System.Int32 dataOffset) [0x00039] in <ab203ffd746f41a2a7492ccf22396d51>:0 
  at Antmicro.Renode.Extensions.Utilities.USBIP.USBIPServer.ReadDeviceDescriptor (Antmicro.Renode.Core.USB.IUSBDevice device) [0x0004b] in <5841826fd70640ecb854de46b76e69e8>:0 
  at Antmicro.Renode.Extensions.Utilities.USBIP.USBIPServer.GenerateDeviceDescriptor (Antmicro.Renode.Core.USB.IUSBDevice device, System.UInt32 deviceNumber, System.Boolean includeInterfaces) [0x00000] in <5841826fd70640ecb854de46b76e69e8>:0 
  at Antmicro.Renode.Extensions.Utilities.USBIP.USBIPServer.HandleListDevicesCommand () [0x00079] in <5841826fd70640ecb854de46b76e69e8>:0 
  at Antmicro.Renode.Extensions.Utilities.USBIP.USBIPServer.HandleIncomingData (System.Int32 b) [0x000b7] in <5841826fd70640ecb854de46b76e69e8>:0 
  at Antmicro.Renode.Utilities.SocketServerProvider.ReaderThreadBody (System.IO.Stream stream) [0x00022] in <ab203ffd746f41a2a7492ccf22396d51>:0 
  at Antmicro.Renode.Utilities.SocketServerProvider+<ListenerThreadBody>c__AnonStorey0.<>m__1 () [0x00000] in <ab203ffd746f41a2a7492ccf22396d51>:0 
  at System.Threading.ThreadHelper.ThreadStart_Context (System.Object state) [0x00017] in <12b418a7818c4ca0893feeaaf67f1e7f>:0 
  at System.Threading.ExecutionContext.RunInternal (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) [0x0008d] in <12b418a7818c4ca0893feeaaf67f1e7f>:0 
  at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) [0x00000] in <12b418a7818c4ca0893feeaaf67f1e7f>:0 
  at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state) [0x00031] in <12b418a7818c4ca0893feeaaf67f1e7f>:0 
  at System.Threading.ThreadHelper.ThreadStart () [0x0000b] in <12b418a7818c4ca0893feeaaf67f1e7f>:0
```

### Do you plan to address this issue and file a PR?

It depends on whether this is an issue or not.

**Comment by DAtz-Alt** [comment]
Another instance of this, in `ReadConfigurationDescriptor` rather than `ReadDeviceDescriptor` — same
root cause, so recording it here rather than opening a duplicate. The pattern is that the server trusts
a device-supplied length and indexes on it without bounds checking, and the failure kills the process
rather than raising an error.

```
Fatal error:
Index was outside the bounds of the array.
   at Antmicro.Renode.Extensions.Utilities.USBIP.USBIPServer.ReadConfigurationDescriptor(IUSBDevice device, Byte configurationId, InterfaceDescriptor[]& interfaceDescriptors)
   at Antmicro.Renode.Extensions.Utilities.USBIP.USBIPServer.GenerateDeviceDescriptor(IUSBDevice device, UInt32 deviceNumber, Boolean includeInterfaces)
   at Antmicro.Renode.Extensions.Utilities.USBIP.USBIPServer.HandleListDevicesCommand()
   at Antmicro.Renode.Extensions.Utilities.USBIP.USBIPServer.HandleIncomingData(Int32 b)
   at Antmicro.Renode.Utilities.SocketServerProvider.ReaderThreadBody(Stream stream)
```

The walk has no bounds check and no zero-`bLength` guard:

```csharp
var currentOffset = Packet.CalculateLength<USB.ConfigurationDescriptor>();
for(var i = 0; i < interfaceDescriptors.Length; i++)
{
    while(recursiveBytes[currentOffset + 1] != (byte)DescriptorType.Interface)
    {
        currentOffset += recursiveBytes[currentOffset];
    }
    ...
}
```
`interfaceDescriptors.Length` comes from `result.NumberOfInterfaces`, and `recursiveBytes` from a second
`HandleSetupPacketSync`. If the device's reply is shorter than the walk expects, `recursiveBytes[...]`
runs off the end. A zero `bLength` would also spin `currentOffset` forever.

This was a device bug on our side, but the server should not die of it.
our device
mis-handled a second consecutive SETUP and re-sent the previous response, so an 18-byte *device*
descriptor was decoded as a configuration descriptor. `bcdUSB = 0x0200` became `TotalLength` and
`bDeviceClass` became `NumberOfInterfaces` — non-zero, so an array was allocated and the walk indexed
past 18 bytes. Any malformed or truncated reply reaches the same place.

## Separate observation on the same function
Even with a *correct* descriptor, the walk miscounts interfaces because it treats **alternate settings
as interfaces**. Our device is CDC-ECM + CDC-ACM, `bNumInterfaces = 4`, and CDC-ECM requires the data
interface to be declared twice (alt 0 with no endpoints, alt 1 with the bulk pair — ECM 1.2 §3: *"The
Data Class interface of a networking device shall have a minimum of two interface settings"*). The four
slots fill with iface0, iface1-alt0, iface1-alt1, iface2 — so the ACM data interface is never reported:

```
$ usbip list -r 127.0.0.1
   : Miscellaneous Device / ? / Interface Association (ef/02/01)
   :  0 - Communications / Ethernet Networking (02/06/00)
   :  1 - CDC Data / Unused (0a/00/00)      <- iface 1, alt 0
   :  2 - CDC Data / Unused (0a/00/00)      <- iface 1, alt 1 (duplicate)
   :  3 - Communications / Abstract (modem) (02/02/00)
```

`lsusb -v` against the same device (kernel parsing the descriptor itself) correctly shows interface 1
twice with `bAlternateSetting` 0 and 1, plus interface 3 as CDC Data. Cosmetic — `attach` is unaffected,
since the kernel re-enumerates — but the fix is to skip descriptors with `bAlternateSetting != 0` when
filling that array.

Note ECM 1.2 §4.3 also requires all alternate settings of a Communications Class interface to share
`bInterfaceClass`/`SubClass`/`Protocol`, so they cannot be told apart by class either — only
`bAlternateSetting` distinguishes them, which is the field being ignored.

ENV:
`renode-infrastructure` master as of 2026-08-21 (`USBIPServer.cs` unchanged functionally since
2024-09-04). Device: an in-tree DWC2 (DWC_otg) gadget model running unmodified TinyUSB firmware; host
Linux with `vhci_hcd`.
