### ISSUE TITLE
Renode fails to start on Windows

### ISSUE THREAD

**Issue by xobs** [renode/renode#566]
### Description

A fresh install on Windows fails to start at all.

### Expected behaviour

Something should happen.

### How to reproduce?

1. Install https://builds.renode.io/renode-latest.msi
2. Run `renode`

### Environment

- OS: Windows 11
- Renode version (with commit SHA): Likely 1.14.0+20231226gitfc5806635

### Additional information

This is what I get when I run `renode`:

```
[5:26:32 pm] E:/Code/Xous> renode

Unhandled Exception: System.TypeInitializationException: The type initializer for 'Antmicro.Renode.Core.EmulationManager' threw an exception. ---> System.TypeInitializationException: The type initializer for 'Antmicro.Renode.Utilities.TypeManager' threw an exception. ---> System.TypeLoadException: Could not load type 'Antmicro.Renode.Utilities.IInterestingType' from assembly 'Emulator, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMarkHandle stackMark, IntPtr pPrivHostBinder, Boolean loadTypeFromPartialName, ObjectHandleOnStack type)
   at System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean loadTypeFromPartialName)
   at System.Type.GetType(String typeName)
   at Antmicro.Renode.Utilities.TypeManager.GetTypeWithLazyLoad(String name, String assemblyFullName, String path)
   at Antmicro.Renode.Utilities.TypeManager.AnalyzeAssembly(String path, Boolean bundled, Boolean throwOnBadImage)
   at Antmicro.Renode.Utilities.TypeManager.ScanInner(String path, Boolean recursive)
   at Antmicro.Renode.Utilities.TypeManager.Scan(String path, Boolean recursive)
   at Antmicro.Renode.Utilities.TypeManager..cctor()
   --- End of inner exception stack trace ---
   at Antmicro.Renode.Utilities.TypeManager.get_Instance()
   at Antmicro.Renode.Peripherals.BackendManager.Init()
   at Antmicro.Renode.Core.Emulation..ctor()
   at Antmicro.Renode.Core.EmulationManager..ctor()
   at Antmicro.Renode.Core.EmulationManager.RebuildInstance()
   at Antmicro.Renode.Core.EmulationManager..cctor()
   --- End of inner exception stack trace ---
   at Antmicro.Renode.Core.EmulationManager.RebuildInstance()
   at Antmicro.Renode.Program.Main(String[] args)
[5:27:28 pm] E:/Code/Xous>
```

**Comment by xobs** [comment]
Note this appears to be caused by installing one version of Renode into the same directory as an earlier version.

There should be a method of upgrading one version to another, or Renode should remove the existing directory if one is found.
